language: python
dist: focal
python:
  - "3.7"
  - "3.8"
install:
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran libffi-dev automake make libtool autoconf g++ m4 pkg-config
  - wget https://github.com/strukturag/libheif/releases/download/v1.10.0/libheif-1.10.0.tar.gz
  - tar xvf libheif-1.10.0.tar.gz && pushd libheif-1.10.0 && ./autogen.sh && ./configure --disable-dependency-tracking && make && sudo make install && popd && rm -rf libheif-1.10.0
  - pip install --only-binary=numpy,scipy -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest tests/test.py -v
