language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran libheif-dev
  - pip install --only-binary=numpy,scipy -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest tests/test.py -v
